while True:
        print("Welcome to game\n if you want guide choose 1\n if you want play game chosse 2")
        chosse = input(":")
        if int(chosse) == 1:
            print("This is game ")
        elif int(chosse) == 2:
            print("Let'go to the game")
            break
#story intro
print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
print("You are the people of the country The Scienture")
print("=======================================================================")
print("As a young scientist working at a Scienture company, you want to createsomething new from what everyone else has done to become a super genius.")
print("=======================================================================")
print("You thought of creating a time-passing gate that could go into both thefuture and the past.")
print("=======================================================================")
print("And today, August 25 2070\nYou have done what everyone thought was impossible That's a\n Time machine.")
print("=======================================================================")
print("But while you're about to bring this project to the country's leaders.")
print("There has been an attack of terrorists who want to rob The Scienture's technology equipment\nand continue to experiment to create weapons to overthrow the country'sleader.")
print("=======================================================================")
print("And when that is the case, the scientists must also be killed.")
print("=======================================================================")
print("In order not to leave the leader's side with the brain to create equipment to fight the terrorists.")
print("=======================================================================")
print("And you're at your lab when you know that terrorists are coming to killyou. From what I heard from the public relations room")
print("=======================================================================")
print("You're unlucky because your lab has the only way out is\nthe normal exit. This means you don't know how to hide or escape.")
print("=======================================================================")
print("In the end, you choose to go back in time to tell the heavens what happened.")
print("=======================================================================")
print("You then start to go back a month to the previous one to make arrangements.")
print("=======================================================================")
print("and at that moment As you are about to pass through time, a terrorist who can invade one person first.")
print("=======================================================================")
print("hat person then uses a gun to shoot at you.")
print("=======================================================================")
print("But he misfired and hit the timer, causing the system to crash.")
print("=======================================================================")
print("But it can also send you narrowly through time.")
print("=======================================================================")
print("When you wake up You meet a girl about 160 tall, dressed strangely.")
name = input("Strange girl:What you name: ")
print("Strange girl:""Hello", name, "\nStrange girl:Oh,I almost forgot My name is Gilda. Nice to meet you")
print(name, ":","Where am I and what year is this?")



